{% set name = "ipyelk" %}
{% set version = "0.1.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/ipyelk-{{ version }}.tar.gz
  sha256: 50b79ee166a2d22e22bdcac968ffa4cdb3ab3c6a032426df65f57286bc79b568

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - ipywidgets >=7.5.0
    - networkx
    - python >=3.7

test:
  imports:
    - ipyelk
    - ipyelk.diagram
    - ipyelk.nx
    - ipyelk.schema
    - ipyelk.tools
  commands:
    - python -m pip check
  requires:
    - pip

about:
  home: https://github.com/jupyrdf/ipyelk
  summary: ELK widget for Jupyter
  license: BSD-3-Clause
  license_file:
    - LICENSE.txt
    - COPYRIGHT.md
    - third-party/epl-v10.html

extra:
  recipe-maintainers:
    - bollwyvl
