{% set name = "ipyelk" %}
{% set version = "2.0.0a0" %}
{% set js_version = version.replace('a', '-alpha').replace('b', '-beta') %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/ipyelk-{{ version }}.tar.gz
  sha256: 7341b9d867529535a87d99996f74b4182107013b8c36c7b17d5b96b88f4f5c3b

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - async-lru >=1,<2
    - ipywidgets >=7.5.0
    - jupyterlab >=3.0
    - networkx
    - python >=3.7
    - pydantic

test:
  imports:
    - ipyelk
    - ipyelk.diagram
    - ipyelk.nx
    - ipyelk.schema
    - ipyelk.tools
    - ipyelk.contrib.elements
    - ipyelk.contrib.library
    - ipyelk.contrib.shapes

  commands:
    - python -m pip check
    - jupyter labextension list  # [unix]
    - jupyter labextension list 1>labextensions 2>&1  # [unix]
    - cat labextensions | grep "@jupyrdf/jupyter-elk.*v{{ js_version }}.*OK.*\(python, {{ name }}\)"  # [unix]
  requires:
    - pip

about:
  home: https://github.com/jupyrdf/ipyelk
  summary: ELK widget for Jupyter
  license: BSD-3-Clause
  license_file:
    - LICENSE.txt
    - COPYRIGHT.md
    - third-party/epl-v10.html

extra:
  recipe-maintainers:
    - bollwyvl
    - dfreeman06
