{% set version = "2.1.0a0" %}
{% set js_version = version.replace('a', '-alpha').replace('b', '-beta') %}

package:
  name: ipyelk
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/i/ipyelk/ipyelk-{{ version }}.tar.gz
  sha256: 18519a12931a7844d973f1773d11bc7861500331028e09b327d6c423b0a775b8

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - flit-core >=3.9.0,<4
    - pip
    - python >=3.8
  run:
    - ipywidgets >=8.0.1,<9
    - networkx
    - pydantic >=1.10.17,<3
    - python >=3.8
  run_constrained:
    - jupyterlab >=4.2

test:
  imports:
    - ipyelk
    - ipyelk.diagram
    - ipyelk.elements
    - ipyelk.loaders
    - ipyelk.pipes
    - ipyelk.schema
    - ipyelk.tools
    - ipyelk.contrib.library
    - ipyelk.contrib.molds

  commands:
    - python -m pip check
    - jupyter labextension list
    - jupyter labextension list 1>labextensions 2>&1
    - grep -iE "@jupyrdf/jupyter-elk.*v{{ js_version }}.*OK" labextensions
  requires:
    - jupyterlab
    - m2-grep  # [win]
    - pip

about:
  home: https://github.com/jupyrdf/ipyelk
  summary: ELK widget for Jupyter
  license: BSD-3-Clause
  license_file:
    - LICENSE.txt
    - COPYRIGHT.md
    - third-party/epl-v10.html
    - src/_d/share/jupyter/labextensions/@jupyrdf/jupyter-elk/static/third-party-licenses.json

extra:
  recipe-maintainers:
    - bollwyvl
    - dfreeman06
