{% set version = "2.0.0" %}
{% set js_version = version.replace('a', '-alpha').replace('b', '-beta') %}

package:
  name: ipyelk
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/i/ipyelk/ipyelk-{{ version }}.tar.gz
  sha256: cddb8fd635bfa8265e300571f3aae501c8f8befbd7440419c7cfc4c109238a68

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps

requirements:
  host:
    - pip
    - python >=3.7
    - flit_core >=3.7.1,<4
  run:
    - ipywidgets >=8.0.1,<9
    - networkx
    - python >=3.7
    - pydantic
  run_constrained:
    - jupyterlab >=3.0

test:
  imports:
    - ipyelk
    - ipyelk.diagram
    - ipyelk.elements
    - ipyelk.loaders
    - ipyelk.pipes
    - ipyelk.schema
    - ipyelk.tools
    - ipyelk.contrib.library
    - ipyelk.contrib.molds

  commands:
    - python -m pip check
    - jupyter labextension list  # [unix]
    - jupyter labextension list 1>labextensions 2>&1  # [unix]
    - cat labextensions | grep "@jupyrdf/jupyter-elk.*v{{ js_version }}.*OK.*\(python, ipyelk\)"  # [unix]
  requires:
    - pip
    - jupyterlab

about:
  home: https://github.com/jupyrdf/ipyelk
  summary: ELK widget for Jupyter
  license: BSD-3-Clause
  license_file:
    - LICENSE.txt
    - COPYRIGHT.md
    - third-party/epl-v10.html
    - src/_d/share/jupyter/labextensions/@jupyrdf/jupyter-elk/static/third-party-licenses.json

extra:
  recipe-maintainers:
    - bollwyvl
    - dfreeman06
